export const ADD = 'ToDoList/ADD'
export const REMOVE = 'ToDoList/REMOVE'
export const EDIT = 'ToDoList/EDIT'
export const SAVE = 'ToDoList/SAVE_EDITION'
export const CANCEL = 'ToDoList/CANCEL_EDITION'
export const COMPLETE = 'ToDoList/COMPLETE'
export const COMPLETE_ALL = 'ToDoList/COMPLETE_ALL'
export const REMOVE_ALL = 'ToDoList/REMOVE_ALL'